x3dom/x3dom

- test/regression-suite/src/resultspublisher.js
Changed workflow of createTimelinePage to make it more roboust to changes
of the test suite. This allows to add new tests without problems caused by
missing entries in the result list of previously run tests.
Different steps of a testcase are aggregated and displayed as one test in
the timeline.
> Regression Tests: Rewrote Timeline Publishing

- src/nodes/Navigation/OrthoViewpoint.js
- src/nodes/Navigation/Viewfrustum.js
- src/nodes/Navigation/Viewpoint.js
This adds support for parent transform of viewpoint node affecting the location of the center of rotation.
> transform center of rotation

- src/nodes/Geospatial/GeoViewpoint.js
and
sync resetView() with Viewpoint.js
> apply current transform in getCenterOfRotation()

- doc/x3doc/base/author/configuration.html
- doc/x3doc/base/author/index.html
- doc/x3doc/base/author/runtime.html
- doc/x3doc/base/developer/index.html
- doc/x3doc/base/static/styles/x3dom-docs-new.css
- doc/x3doc/tmpl/classContainer.tmpl
- doc/x3doc/tmpl/classFields.tmpl
- doc/x3doc/tmpl/classSummary.tmpl
- doc/x3doc/tmpl/indexedContent.tmpl
- doc/x3doc/tmpl/layout.tmpl
- doc/x3doc/tmpl/params.tmpl
- doc/x3doc/tmpl/properties.tmpl
Remaining adaptions for new documentation design.
> New documentation design (2)

- src/nodes/Geospatial/GeoTransform.js
Please ignore previous pull request as  this pull request can be automatically merged.
This implements fully the GeoTransform node as specified in the ISO spec.. An additional, experimental option is provided as a field with the name globalGeoOrigin. The option was discussed on the geospatial x3d mailing list.
> GeoTransform implementation

- src/X3DCanvas.js
full resolution on high res devices
> scale canvas resolution to device resolution, rather then css resolution

- src/X3DCanvas.js
i managed to accidentally add a semicolon in my code before committing, and it got merged into x3dom/x3dom and broke the dev build.....
> IMPORTANT fix the stray semicolon which broke x3dom

- src/nodes/VolumeRendering/IsoSurfaceVolumeData.js
- src/nodes/VolumeRendering/SegmentedVolumeData.js
- src/nodes/VolumeRendering/VolumeData.js
- src/nodes/VolumeRendering/X3DVolumeDataNode.js
This should fix the problem reported in issue #537 allowing to move the camera inside the volume.
> Feature allow to locate the camera inside the volume

- src/nodes/Text/FontStyle.js
> fontstyle doc. update

- src/util/Parts.js
- fix error in setEmissiveColor from xback to xBack
> Fix error for setEmissiveColor

- src/nodes/Rendering/IndexedTriangleStripSet.js
Add test on last value on indices during initialisation in nodeChanged (same as IndexFaceSet source)
> fix #599, index of IndexTringleStripSet can end with any value

- src/nodes/Geospatial/GeoLOD.js
This is a (simplistic) implementation for the GeoLOD node. It works with all tested examples on web3d.org which use this node. Once loaded, there is no attempt to unload levels if they are out of range. So beware of very large LODs. Another todo item is to preload levels which are getting close to smooth the transition between levels.
> GeoLod implementation

- src/nodes/VolumeRendering/MPRVolumeStyle.js
Allows the use of a transfer function in the MPRVolumeStyle. References issue #613.
> Added transferFunction argument to the MPRVolumeStyle

- src/nodes/Navigation/X3DViewpointNode.js
typo in a rarely used function;
> typo; missing semicolon

- src/X3DCanvas.js
This PR introduces `X3DCanvas.bindEventListeners()` method and moves all event bindings. 
Before the event handlers are bound they are set as properties to the X3DCanvas instance. The old approach used anonymous functions which prevented developers to extend the default interaction. 
With this PR we are now able to add mouse+keyboard combinations such as __mouseWheel + Alt key__ . Simple implementation could be:
``` js
var d = function(selector) { return document.querySelector(selector)}
x3dom.runtime.ready = function() {
var x3d = d('x3d');
var viewpoint = d('viewpoint');
var x3dCanvas = x3d.runtime.canvas;
var _onMouseWheel = x3dCanvas.onMouseWheel;
x3dCanvas.onMouseWheel = function(event) {
if(event.altKey) {
var offset = .01
var fov = parseFloat(viewpoint.getAttribute('fieldofview')) …
```
> Expose canvas event handlers

- src/gfx_webgl.js
- src/nodes/Geometry3D/ExternalGeometry.js
- src/util/glTF/glTFLoader.js
#695 
fixed old SRC based externalGeometry rendering
> Src compatibility fix

- src/util/glTF/glTFContainer.js
- src/util/glTF/glTFLoader.js
This push request fixes the problems mentioned in #702.
Now the duck is rendered with lighting.
- fixed usage of default technique parameter values
- fixed usage of duplicated semantics for different shader uniforms
> fixed usage of default technique parameter values

- src/nodes/Navigation/modes/TurntableNavigation.js
- src/util/glTF/glTFLoader.js
#698
I have fixed some Issues with the Turntable Navigation Mode.
- fixed Zoom
- fixed switching between Navigation Modes
- fixed double click to change center of rotation
> fixed Turntable Navigation

- src/util/RequestManager.js
In one of our applications we need want to show download progress of x3dom. This PR adds callbacks one can overwrite to be informed when x3dom downloads change. As parameter some stats are handed into callbacks.
> Added hooks to RequestManager

- src/util/glTF/glTFContainer.js
- src/util/glTF/glTFLoader.js
Fixed the support for using multiple textures and added support for non-power-of-two textures with resizing when needed.
Should fix all the problems in #707 
Also added a texture cache, so that the glTF Textures are not loaded multiple times.
> glTF texture fix

- src/util/glTF/glTFContainer.js
> small fix for glTF loader

- src/nodes/Geospatial/GeoViewpoint.js
to allow use of GeoViewpoint in Inline.
Addresses #726.
https://gist.github.com/andreasplesch/547fdac4ef3862f435e531c91ce871e8/raw/378e34b91d7f7f13c24219b5bd1a457513234b0e/x3dom_geovp.user.js
is a user script to test this PR with Tampermonkey.
> GeoViewpoint: initialize this._viewMatrix

- src/nodes/Geospatial/GeoCoordinate.js
- src/nodes/Geospatial/GeoTransform.js
- src/util/EarClipping.js
lgtm.com detected some missing local var declaration in code I had touched:
https://lgtm.com/projects/g/x3dom/x3dom/snapshot/8379ebcb4fe24e55089cae1fb1883ea2b99cd450/files/src/util/EarClipping.js
https://lgtm.com/projects/g/x3dom/x3dom/snapshot/8379ebcb4fe24e55089cae1fb1883ea2b99cd450/files/src/nodes/Geospatial/GeoTransform.js
and some formatting issues here:
https://lgtm.com/projects/g/x3dom/x3dom/snapshot/8379ebcb4fe24e55089cae1fb1883ea2b99cd450/files/src/nodes/Geospatial/GeoCoordinate.js
The PR fixes those issues.
> fixes for LGTM

- src/Viewarea.js
- src/nodes/EventUtilities/BooleanFilter.js
- src/nodes/EventUtilities/BooleanSequencer.js
- src/nodes/EventUtilities/BooleanToggle.js
- src/nodes/EventUtilities/BooleanTrigger.js
- src/nodes/EventUtilities/IntegerSequencer.js
- src/nodes/EventUtilities/IntegerTrigger.js
- src/nodes/EventUtilities/TimeTrigger.js
- src/nodes/EventUtilities/X3DSequencerNode.js
- src/nodes/EventUtilities/X3DTriggerNode.js
- src/nodes/Geospatial/GeoCoordinate.js
- src/nodes/Geospatial/GeoTransform.js
- src/util/EarClipping.js
- tools/packages.json
generate touchsensor events (isActive, touchtime) when pressed but not moved
> static mouse press fix

- src/nodes/EventUtilities/X3DSequencerNode.js
enable key and keyValue output events without looping
> Sequencer key output

- src/fields.js
during regex parsing of field values. This allows, for example, mavo expression in fields.
> guard null matches

- src/X3DDocument.js
to conform to x3d spec. recommendation. fixes #778
> flip PgUp/PgDn

- src/X3DCanvas.js
for PgDn,PgUp,Space presses to not scroll. fixes #779
> prevent keypress default action

- src/gfx_webgl.js
> calc. pick with shader 'from'

- src/nodes/Shape/Shape.js
by dirty all after deleting child (Appearance). Fixes #820.
> allow for correct removal of Appearance nodes

- src/JSONParser.js
- src/nodes/Networking/Inline.js
- tools/packages.json
Proof of test here:
https://coderextreme.net/X3DJSONLD/src/main/html/x3domexamples3.html
https://coderextreme.net/X3DJSONLD/src/main/html/x3domexamples4.html
https://coderextreme.net/X3DJSONLD/src/main/html/x3domexamples5.html
> Enhancements for adding for X3D JSON Parser for JSON encoding and JSON Inlines -- Only

- src/nodes/Networking/Inline.js
> see #837, then got rid isJSON and parse instead

- src/util/json/JSONParser.js
This was a warning from lgtm.   I removed the offending lines.
John
> Removed setting values when not used (not tested, pull at your own risk).

- src/Runtime.js
- test/functional/runtime.html
runtime.html enhancements for createX3DFromJS
> Browser sai

- src/Internals.js
- src/fields.js
This PR is a simple first attempt fix-up of 2 files:
* Internals.js
* fields.js
It is by no means an extensive clean up and the doc blocks still need a lot more work, this is really just a first pass over some of the existing JSDoc to bring it more towards standards. There are still a number of functions which need blocks adding, and a number of blocks need @return @param adding/embellishing.
This is really more of a feeler PR - If this sort is something you are interested in, I am more than happy to progress further and go over each file in more detail. I would really love to contribute to x3dom in any way I can.
@andreasplesch I notice in your PR #867 you are also touching fields.js - hopefully there would be no conflict as you are simply adding a new function.
> First pass JSDoc fix-up

- src/Bindable.js
- src/Cache.js
- src/Docs.js
- src/Internals.js
- src/debug.js
- src/fields.js
- src/gfx_webgl.js
Standardise formatting, parenthesis, comments and JSDoc across files Bindable.js to Internals.js
These files had a right mixed bag of formatting and indenting!
* Added JSDoc headers to all functions.
* Indenting 4 spaces, no tabs.
* Collapsed if / else statements.
I don't know if this is a bit too big a change as this diff is quite large. 
Do let me know if you would prefer I went a little slower or broke this down into smaller PR's.
> Lint & formatting of Bindable.js -> Internals.js

- src/Mesh.js
Formatting, whitespace fix-ups and JSDoc for Mesh.js.
> Lint Mesh.js

- src/nodes/H-Anim/HAnimHumanoid.js
- src/nodes/H-Anim/HAnimJoint.js
> HAnim small typos

- src/SSAO.js
* Format SSAO.js 
* Add file header.
* Small embellishment of JSDoc blocks.
Spot checks of various regression-suite tests all run OK.
> Lint SSAO.js

- src/Runtime.js
Format and whitespace alignment of Runtime.js
First pass tidy up of JsDoc blocks added @param etc.
Spot checks of various regression-suite tests all run OK.
> Lint Runtime.js

- src/Texture.js
Format and whitespace alignment of Texture.js
First pass tidy up of JsDoc blocks added @param etc.
Spot checks of various regression-suite tests all run OK.
> Lint Texture.js

- src/Viewarea.js
Format and whitespace alignment of Viewarea.js
First pass tidy up of JsDoc blocks added @param etc.
Spot checks of various regression-suite tests all run OK - in particular tested mouse interactions.
> Lint Viewarea.js

- src/gfx_webgl.js
Before I started renaming BufferGeometryView to BufferView for #898 I noticed the regression tests were failing. Looks like merge fallout between my linting and the webVR branch. 
This only affects the WebVr branch, master is OK.
> THINKABOUTME merge conflict fix

- src/shader/ShaderDynamic.js
> pbr base color is factor for vertex color

- src/nodes/Shape/X3DShapeNode.js
- src/util/Utils.js
rather than count, to allow for simultaneous adding and removing.
live at https://raw.githack.com/andreasplesch/x3dom/a2e5639963c50ef1218ba2174d0774aca37635fe/test/functional/inline-gltf.html
This change required the least modifications but there may be better ways.
> dirty lighting by full array

- src/util/glTF/glTF2Loader.js
> gltf extras as metadata

- src/util/glTF/glTF2Loader.js
for extreme zfar values, fixes #931
> limit zfar/znear ratio

- src/nodes/Lighting/PhysicalEnvironmentLight.js
- src/nodes/Shape/PhysicalMaterial.js
#924, and doc updates for PhysicalMaterial
> doc updates

- src/nodes/Navigation/modes/DefaultNavigation.js
use explorationMode as bitmask for buttonState
> fix exploration mode for examine

- src/nodes/VolumeRendering/ProjectionVolumeStyle.js
- src/nodes/VolumeRendering/X3DVolumeDataNode.js
Solves visual artefact problem in the enter-exit corners of the volume data, because the casted ray does not traverse the whole volume data from certain view angles.
> Fixes bug, causing visual artefact on the volume rendering visualization

- src/nodes/VolumeRendering/MPRPlane.js
Added an additional boolean field `enabled` to the MPRPlane node, Refs #944.
```xml
<MPRPlane enabled="false"></MPRPlane>
```
Allows to dynamically make the reconstructed plane visible or not visible.
> Allow to enable/disable each MPR plane individually

- src/Viewarea.js
- src/gfx_webgl.js
- test/functional/carousel.html
- test/regression-suite/test/cases/picking/picking.html
as discussed on the mailing list: https://sourceforge.net/p/x3dom/mailman/message/36676349/
> fix layerXY for high DPR (mobile)

- src/nodes/Texturing/MatrixTextureTransform.js
- src/nodes/Texturing/TextureTransform.js
- src/nodes/Texturing/X3DTextureTransformNode.js
- src/util/glTF/glTF2Loader.js
- tools/packages.json
> Textrafo gltf mode

- doc/misc/iX/sonnensystem_x3dom.html
- src/gfx_webgl.js
- test/functional/runtime.html
- test/regression-suite/test/cases/cubemap/cubemap.html
addresses #972.
Create cubemap texture in dds order since dds shader is used now.
addresses #971 
guard against undefined eyeIdx
> fix Background face order and undefined eyeIdx

- RELEASENOTES.rst
Updating release notes in preparation for 1.8.1.
Also some small tidy up / standardisation of formatting.
> Added v1.8.1 to release notes.

- src/shader/ShaderDynamic.js
> allow textrafo for sphere mapping

- src/fields.js
> fix and simplify SFImage parsing

- src/util/glTF/glTF2Loader.js
> generate name for material if not given

- src/X3DDocument.js
- src/gfx_webgl.js
- src/nodes/Grouping/X3DTransformNode.js
- src/nodes/Networking/Inline.js
- test/functional/memory.html
> lgtm warnings

- build/jsdoc/jsdoc-template/base/tutorials/largeModels/culling/example.html
- build/jsdoc/jsdoc-template/base/tutorials/lighting/gamma/example.html
- src/fields.js
- src/util/DDSLoader.js
- src/util/glTF/glTF2Loader.js
mostly semicolons
https://lgtm.com/projects/g/x3dom/x3dom/alerts/?mode=list&severity=
> real LGTM nitpicks

- src/Texture.js
add rim for better mipmaps, max anisotropic, horizontal space
> improve small text

- src/Texture.js
small fonts have proper hinting for their size
> use smaller fonts for higher mips

- src/nodes/NURBS/x3dom-nurbs-web-worker.js
- src/nodes/Time/TimeSensor.js
and resume at paused fraction by adjusting startTime accordingly
> Pause time

- src/nodes/Geometry3D/Sphere.js
invert normals for ccw=false, more specific geocache ID, simplifications
> Sphere ccw, geocache, simpler

- src/nodes/Geometry3D/Box.js
invert normal if ccw=false, ccw in cache id
> Box ccw, geocache

- src/nodes/Geometry3D/Cylinder.js
invert normal for ccw=false, use ccw for cache id
> Cylinder ccw, geocache

- src/nodes/Geometry2D/ArcClose2D.js
- src/nodes/Geometry2D/Disk2D.js
- src/nodes/Geometry2D/Rectangle2D.js
- src/nodes/Geometry3D/Cone.js
- src/nodes/Geometry3D/Plane.js
invert normals if ccw=false for Plane, Cone, Disk2D, ArcClose2D and Rectangle2D
> ccw for various primitives 

- src/Viewarea.js
fixes generation of isOver=false events
> find correct touchsensors on mouseout

- test/functional/galaxy.html
Game mode works fine  on galaxy.html
> Add game mode to select options in HUD

- src/gfx_webgl.js
> disable FP_TEXTURES on iDevices

- src/X3DDocument.js
Add missing key commands to help info shown in debug window.
> Extend help shown in debug window

- src/nodes/EventUtilities/BooleanToggle.js
> toggle_changed on set_toggle

- CHANGELOG.md
- src/shader/ShaderDynamic.js
> discard relative to transparency

- src/nodes/PointingDeviceSensor/TouchSensor.js
plus non standard hitRotation field, from local Up to local hit normal.
> hit output fields for TouchSensor

- build/jsdoc/jsdoc-template/base/author/runtime.html
- src/Runtime.js
> alias runtime calcPagePos and calcCanvasPos

- src/gfx_webgl.js
- src/nodes/BVHRefiner/BVHRefiner.js
- src/nodes/CADGeometry/CADFace.js
- src/nodes/Geospatial/GeoLOD.js
- src/nodes/Grouping/Switch.js
- src/nodes/Grouping/X3DBoundedObject.js
- src/nodes/Grouping/X3DTransformNode.js
- src/nodes/Navigation/LOD.js
- src/nodes/Rendering/TriangleSet.js
- src/nodes/Shape/X3DShapeNode.js
- src/util/DrawableCollection.js
- test/regression-suite/test/cases/cadTeapot/cadTeapot.html
as alias for render, for X3D 4.0.
resolves #1103
> add visible field

- CHANGELOG.md
- src/nodes/Geometry3D/Cone.js
- src/nodes/Geometry3D/Cylinder.js
refactor, bottom/side/solid were already changeable
> v4 cone cylinder

- src/fields.js
> fix Array.map

- src/NodeNameSpace.js
- src/X3DDocument.js
> check if node already added to graph

- src/util/BinaryContainerSetup.js
> clean up only if cache not needed

- src/Viewarea.js
- src/gfx_webgl.js
use only on=true lights for light matrix array for shadows.
> only on lights for shadow light matrix

- src/Viewarea.js
> provide early light matrix

- CHANGELOG.md
- src/X3DCanvas.js
- src/X3DDocument.js
- src/fields.js
- src/gfx_webgl.js
- test/functional/runtime.html
> fix X3D element mutation

- src/util/json/JSONParser.js
> HAnim containerfields

- src/shader/ShaderDynamic.js
which also sets sp.alphaCutoff
> reenable nonPBR alphaclipthreshold

- CHANGELOG.md
- src/Internals.js
- src/NodeNameSpace.js
- src/NodeNameSpaceProtos.js
- src/X3DDocument.js
- src/nodes/Networking/Inline.js
- test/functional/exportimport/ExportExample.x3d
- test/functional/exportimport/ExportExternProtoExample.x3d
- test/functional/exportimport/ExportProtoExample.x3d
- test/functional/exportimport/ImportExample.html
- test/functional/exportimport/ImportExternProtoExample.html
- test/functional/exportimport/ImportProtoExample.html
- test/functional/exportimport/ProtoExample.x3d
Support IMPORT/EXPORT node.
[https://github.com/x3dom/x3dom/issues/1166](https://github.com/x3dom/x3dom/issues/1166)
> importExportSupported

- src/gfx_webgl.js
- src/shader/ShaderDynamicPicking.js
addresses https://github.com/x3dom/x3dom/issues/1150
> support for Point Properties picking

- src/nodes/Core/X3DNode.js
> guard for adding Statements

- src/nodes/Geometry3D/Plane.js
> declare nSign

- src/NodeNameSpaceProtos.js
> decrement download count after externproto loading

- src/util/protos/ProtoDeclaration.js
> forward events into ProtoInstance

- CHANGELOG.md
- src/nodes/Geometry3D/IndexedFaceSet.js
> allow creaseAngle for coord field updates

- CHANGELOG.md
- src/nodes/Interpolation/ColorInterpolator.js
- src/nodes/Interpolation/CoordinateInterpolator.js
- src/nodes/Interpolation/NormalInterpolator.js
- src/util/BinaryContainerSetup.js
- src/util/json/JSONParser.js
buffer support for Coordinate, Normal, and ColorInterpolator
> additional buffer interpolators 

- CHANGELOG.md
- src/nodes/Lighting/SpotLight.js
> beamWidth default update

- CHANGELOG.md
- src/nodes/Navigation/NavigationInfo.js
> guard against null viewarea

- CHANGELOG.md
- src/nodes/Interpolation/ColorInterpolator.js
for ColorInterpolator used in Background by initializing last color.
> allow 0,0,0 as first color

- src/util/DDSLoader.js
- src/util/Utils.js
allow back up urls for ImageTexture
> Urls for ImageTexture

- CHANGELOG.md
- src/nodes/Networking/Anchor.js
- test/functional/protos/ArtDecoExamplesExcerpt.x3d
- test/functional/protos/ArtDecoPrototypesExcerpt.x3d
- test/regression-suite/test/cases/inlineEvents/inlineEvents.html
and replace current scene if x3d
> enable Anchor back-up urls

- CHANGELOG.md
- src/nodes/Geometry3D/IndexedFaceSet.js
> better indices for concave IFS

- CHANGELOG.md
- src/nodes/Grouping/Scene.js
see #1214
commit seems straightforward but not tested due to lack of test data.
> shadowIdMap: replace eval with JSON.parse

- CHANGELOG.md
- src/nodes/Shaders/ComposedShader.js
- test/regression-suite/test/cases/volrenOpacity/volrenOpacity.html
see #1214, tested with ComposedShader  and volren test.
> safe ComposedShader fields parsing

- src/Viewarea.js
- src/nodes/Core/X3DNode.js
- src/nodes/Networking/Inline.js
to avoid unnecessary CSP errors
> check for existence of onevent attributes

- CHANGELOG.md
- src/NodeNameSpace.js
> attach field functions to USE dom nodes

- CHANGELOG.md
- src/Texture.js
- src/nodes/Texturing/Texture.js
- test/regression-suite/test/cases/movieTexture/movietexture.html
node removal (#1226), ios, autostart
> MovieTexture fixes

- src/Texture.js
- src/nodes/Texturing/Texture.js
Remove invalid commits of #1228 .
> Texture.js: Add a guard to prevent setInterval() from being called repeatedly

- CHANGELOG.md
- src/gfx_webgl.js
> disable depth write for transparency

- CHANGELOG.md
- src/gfx_webgl.js
- src/nodes/Shape/Appearance.js
- src/nodes/Texturing/X3DTextureNode.js
enable default depth write for textured shapes
auto sort type for textured shapes based on auto channel count
> transparent texture handling

- CHANGELOG.md
- src/shader/ShaderDynamic.js
- src/util/glTF/glTF2Loader.js
Improve glTF alphaCutoff for material
> glTF material.alphaCutoff

- .github/workflows/pull_request.yml
- CHANGELOG.md
- src/Main.js
- src/NodeNameSpace.js
- src/X3DDocument.js
exclusively to avoid duplicate events and loading
> field updates through mutations

- CHANGELOG.md
- src/nodes/BVHRefiner/BVHRefiner.js
- src/nodes/CADGeometry/CADFace.js
- src/nodes/Geospatial/GeoLOD.js
- src/nodes/Grouping/Switch.js
- src/nodes/Grouping/X3DBoundedObject.js
- src/nodes/Grouping/X3DGroupingNode.js
- src/nodes/Grouping/X3DTransformNode.js
- src/nodes/H-Anim/HAnimHumanoid.js
- src/nodes/H-Anim/HAnimJoint.js
- src/nodes/Layout/ScreenGroup.js
- src/nodes/Navigation/Billboard.js
- src/nodes/Navigation/Collision.js
- src/nodes/Navigation/LOD.js
- src/nodes/Navigation/X3DLODNode.js
- src/nodes/Shape/X3DShapeNode.js
- test/regression-suite/test/cases/routes/routes.html
along with bboxMarign and bboxColor. collectDrawables adds a bbox shape if displayed, even if node is not visible.
> bboxDisplay field

- src/Viewarea.js
- src/X3DCanvas.js
- src/util/VRControllerManager.js
- Improved the zoom functionality in VR mode by using viewpoint info
- Fixed the issue of VR mode crashing when a VR controller goes out of sensor view
> VR zoom and controller fix

- CHANGELOG.md
- build/jsdoc/jsdoc-template/tmpl/classFields.tmpl
- src/Docs.js
- src/Main.js
- src/NodeNameSpace.js
- src/Runtime.js
- test/functional/runtime.html
allow custom baseURL as X3D attribute, other fixes
> baseURL parameter, docs

- CHANGELOG.md
- src/util/glTF/glTF2Loader.js
> survive null glTF scene.nodes

- CHANGELOG.md
- src/nodes/Core/X3DBindableNode.js
> add isBound and bindTime output
