x3dom/x3dom

- src/nodes/Geometry3DExt/ElevationGrid.js
SPHERE-LOCAL mode (and other modes when implemented) supported by calling _mesh.calcTexCoords(), in the same way as other mesh generating nodes such as IndexedFaceSet.
When both TextureCoordinate and TextureCoordinateGenerator nodes are provided, TextureCoordinateGenerator may take precedence. Not sure what the spec. suggests for this case.
Here is a scene which uses SPHERE-LOCAL mode with the patch:
http://andreasplesch.github.io/x3dom/GeoElevationGrid_texture/terrain_sphere-local.xhtml
> ElevationGrid: improved TextureCoordinateGenerator support 

- src/fields.js
The .setPixels() expects a pixels array, but the image array was provided.
Instead of converting to and from Pixels, it may be possible to just copy the array using the slice method  ?
> SFImage.copy function bug

- src/NodeNameSpace.js
A small fix to address the case:
1) existing node._vf.someBoolean = 'false'
2) try to use node.setFieldValue('someBoolean', true)
3) current if clause in line 141 evaluates to false -> no update (!)
4) instead properly check for existence of field someBoolean as intended
I can probably put together a simple test case if needed.
> setFieldValue if existing Bool value == false

- src/Texture.js
- src/nodes/Text/FontStyle.js
The PR addresses issue #545. It adds proper positioning and support for all combinations these fields of the FontStyle node:
- justify: added minor alignment, including for FIRST
- topToBottom: added false (bottom to top)
The horizontal=false and leftToRight=false options are not or only partially supported due to lack of these features in canvas text rendering by web browsers.
The default for justify is modified to MIDDLE MIDDLE for backwards compatibility.
Also, the text node length and maxExtent fields are implemented except that text length will only be shortened and never expanded.
> improve text fontstyle support

- src/fields.js
addresses #560.
Test by clicking button in http://andreasplesch.github.io/x3dom/x3dom_text/
> fix for escaped quotes in text node

- src/util/EarClipping.js
This PR streamlines and enhances Earclipping further by
- replacing counter based aborting with time out
- avoiding an inner loop as often as possible
At the same time, some code could be removed reducing the total lines of code.
All tests still work and some more complicated polygons now mesh. The time out is set to 5s per polygon and could be adjusted to a higher (or lower) period.
> further improved Earclipping

- src/util/EarClipping.js
This PR replaces the earclipping algorithm with a more efficient earclipping library available here:
https://github.com/mapbox/earcut
The main advantage is handling of corner cases and large polygons. 
The dedicated library is compact and included directly in EarClipping.js but it could be moved to a separate file.
There is some required remapping of input and output to and from the library which could be optimized by directly using the provided x3dom linkedlist.
The library also deals with holes in polygons if needed elsewhere (fonts?) at some point.
This user script allows for testing:
https://gist.githubusercontent.com/andreasplesch/42d6405d0de8cc2472b8/raw/x3domEarcut.user.js
> use mapbox/earcut library for efficient earclipping

- src/nodes/Text/Text.js
An empty array for mesh vertex positions leads to a 0 volume for getVolume(). This in turn leads to small feature culling in renderedTexture (and when otherwise requested as it seems to be switched on now by default). This is why text does not display in VR.
The fix simply provides some non-null geometry which leads to initial non-null volume. SInce then text is not culled, the mesh positions get updated to the real geometry (in Texture.js) and getVolume() will get the real volume.
> fix text for VR (rendered texture)

- src/X3DCanvas.js
Picking was broken on scaled displays, e.g. Windows scaled to 125% for high DPI display devices. This can easily be seen in the picking demo, but applied equally to any combined use of runtime.mousePosition, runtime.pickRect, or accessing Event.hitPnt.  The coordinates returned for a MouseEvent did not account for the previous use of scaling on the 3d canvas element, resulting in a visible offset between the physical mouse position and the logical position computed by mousePosition.  Scaling the result of this function corrects the issue.
> Apply devicePixelRatio to canvas coordinates on scaled displays

- doc/x3doc/base/author/runtime.html
- src/Runtime.js
- test/functional/measurescale.html
Implemented a new runtime function getPixelScale to get the virtual world scale of a pixel for orthographic viewpoints.
Runtime docs have been updated and a test example has been created in ./test/functional/measurescale.html
> added getPixelScale runtime function for orthographic views

- manage.py
- tools/jspacker.py
- tools/packages.py
- tools/x3dom_packer.py
In reference to issue # #661 This should help with the support for both python 2.7 and 3.5 users to use the `manage.py` script.
Tested the following commands:
```
python manage.py --runserver
python manage.py --build
python manage.py --stats
```
> Added compatibility with python 3 and 2 for manage.py

- src/X3DDocument.js
This PR adds selection of parent node for nodes inside of `<X3DOMMetaGroup>`s as described in #693.
PS: Due to my IDE setup also surplus white-space was removed. If you want to keep that, let me know and I update the PR...
> Fix for issue #693

- src/util/glTF/glTFContainer.js
- src/util/glTF/glTFLoader.js
#695
When using multiple ExternalShapes with glTF-models there was an error with the VertexAttributes, so that some models may not be rendered. This is fixed now.
In addition when no Material is present, the KHRMaterialCommons Material with constant shading is used by default now.
> fixed glTF Rendering Problems

- src/util/RequestManager.js
The `abortAllRequests`-function in RequestManager uses one line variable assignment which leads to `this.requests` and `this.activeRequests` referencing the same object after _reset_. Hence in next run requests _active_ as soon as stored on `this.requests`.
> Fix reset of request queues in RequestManager

- src/util/RequestManager.js
I have noticed that when one aborts all requests via Request Managers the counters are not reset. When one starts new requests afterwards, the counters show wrong results e.g. total considers the also aborted requests so loaded count can never again equal with total requests.
> Reset RequestManger counters when all requests are aborted

- src/Mesh.js
Fix https://github.com/x3dom/x3dom/issues/411
The X3Dom default UV mapping is not respecting well the X3D reference:
http://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/components/geometry3D.html#f-IndexedFaceSettextureDefaultMapping
The issue is that the second UV coordinate (aka `T`) should be truncated by the first coordinate (aka `S`).
[default-mapping.zip](https://github.com/x3dom/x3dom/files/1124198/default-mapping.zip)
Note: I tested on my implementation and on Blender giving the same results.
| Original | Patched | Reference (my implementation) |
| --- | --- | --- |
| ![capture d ecran 2017-07-05 a 11 40 48](https://user-images.githubusercontent.com/866788/27858789-d824bc26-6176-11e7-95e5-fd94d107c9f7.png) | ![capture d ecran 2017-07-05 a 11 39 …
> Fix default UV mapping

- doc/x3doc/base/static/styles/x3dom-docs-new.css
Earlier today I tried reading your documentation page for IndexedFaceSet on my iPad. The entire page was zoomed out to accommodate the &lt;code&gt; element near the top, making it impossible to read without zooming in. Even for browsers that do not zoom out for extremely long lines, most of the text will be outside of the visible window and not easily accessible.
This small change keeps the HTML encoding of the node and all of its defaults in a compact wrapped area where everything is easily seen, making the documentation more useful.
> Let <code> elements wrap white space

- src/nodes/Rendering/CoordinateDouble.js
- tools/packages.json
This node may help with scene compatibility across x3d browser. Example use: https://jsfiddle.net/fzzgso28/1/
Also see http://web3d.org/pipermail/x3d-public_web3d.org/2017-September/007421.html and thread for some discussion.
The CoordinateDouble.js file was placed next to Coordinate.js file in the Rendering folder although it belongs with Nurbs component. Feel free to move to another location.
> CoordinateDouble node implementation

- src/shader/ShaderKHRMaterialCommons.js
https://github.com/KhronosGroup/glTF/tree/master/extensions/Khronos/KHR_materials_common defines the transparency property as providing opacity values, with a default of 1.0 for no transparency. All official glTF examples use the default.
https://rawgit.com/andreasplesch/gltf-test/Binary-MC/index.html provides the models. Without the transparency fix all models are displayed as completely transparent.
https://rawgit.com/andreasplesch/gltf-test/addLight/index.html applies the fixed shader from this PR to all example models. With it the models are displayed.
There are other issues with specular colors and node transforms which may be addressed separately.
This PR addresses #758.
> gfTF khr material commons transparency/specular fix

- src/util/glTF/glTFContainer.js
glTTF nodes using a KHR Material Commons material also needed to have their world transform applied, in the same ways as #723 does for generic glTF material nodes.
This addresses #761 .
https://rawgit.com/andreasplesch/gltf-test/kmcTransforms/examples/x3dom/index.html?category=sampleModels&model=CesiumMilkTruck&scale=0.5&type=glTF-Binary-MaterialsCommon
uses this fix (and #759)
https://rawgit.com/andreasplesch/gltf-test/kmcTransforms/index.html provides viewing of all other sample models with this patch (and #759).
> glTF kmc trafos fix

- src/nodes/VolumeRendering/MPRVolumeStyle.js
This pull request allows to define translucent planes with a transfer function in the MPRVolumeStyle. 
This feature can be enabled by setting the new field __forceOpaque__ to _false_. By default, this new value is set to true, in this way it maintains compatibility with previous behaviour of defining opaque planes.
This is a first step towards issue #755  
Scene definition example:
```
<VolumeData id='volume' dimensions='1 1 1' render='true'>
<ImageTextureAtlas containerField='voxels' url='aorta4096.png' numberOfSlices='96' slicesOverX='10' slicesOverY='10'/>
<MPRVolumeStyle id='style' positionLine='0.5' forceOpaque="false">
<ImageTexture containerField='transferFunction' url='tf.png'/>
</MPRVolumeStyle>
</VolumeData>
```
> Added a new field to allow traslucent planes in the MPRVolumeStyle with a transfer function

- src/X3DCanvas.js
- src/nodes/Navigation/NavigationInfo.js
This PR adds a property called `naturalScoll` to the NavigationInfo-Node, which inverts the scroll-events and thus fixes #486.
> Add property to NavigationInfo for natural Scrolling. Fixes #486

- doc/x3doc/base/tutorials/basics/imagesMovies/example.html
This image produces a CORS redirection error in Safari, but not in Chrome or Firefox. This simple edit solves that particular problem.
> Avoid CORS error

- src/nodes/Texturing/X3DTextureNode.js
When removing a VolumeData node from an X3D scene, the volume isn't removed and a console error is generated ':
Uncaught TypeError: Cannot set property 'texture' of undefined. See this example:
https://scalablebrainatlas.incf.org/x3bug/aorta_remove.xhtml
The added check in line 191 fixes the problem. I do not know what is really causing the error, whether more elegant solutions exist, and whether perhaps a similar fix is needed in line 175. The following page illustrates the desired behavior after the fix:
https://scalablebrainatlas.incf.org/x3bug/aorta_remove_fixed.xhtml
> fix parentRemoved function

- src/nodes/Navigation/Viewpoint.js
I noticed a discrepancy in the documentation for this default value:
http://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/components/navigation.html#Viewpoint
This was presumably a simple transposition typo, since a rotation about a zero axis makes no sense.
> Correct default orientation

- src/shader/ShaderDynamic.js
ComposedCubeMapTexture stopped working after cs shader environment map was introduced because the environmentFactor uniform was not available or 0.0. This PR applies environmentFactor in the shader only for cs shader cases and thereby restores the X3D ComposedCubeMapTexture node.
> ignore EnvironmentFactor for CubeMapTexture node 

- src/X3DCanvas.js
The call to this._initContext with five parameters does not match the function itself, which has four parameters. This is because in the call, the parameter for "flashie" is pased as the fourth parameter, while in the function itself this parameter has been removed. As a consequence, one could not use the tag <X3D backend="webgl2"> to invoke a webgl2 context, because the 'tryWebGL2' parameter is lost as the fifth parameter. The proposed change fixes this error.
> Update X3DCanvas.js to enable webgl2 context.

- src/gfx_webgl.js
In the old code, only 'experimental-webgl2' was tested as a context that invokes webgl2, and the name 'webgl2', which is used by most current browsers, is not tested. The proposed change fixes that error.
> Update gfx_webgl.js to enable webgl2 context

- doc/x3doc/base/author/index.html
- doc/x3doc/base/developer/index.html
These two documentation files are both static, so the reference to generation is misleading. In the event that changes in the future, I just commented out the two references.
> Remove reference to generation

- src/nodes/Navigation/LOD.js
- src/nodes/Networking/Inline.js
The Lod outputOnly level_changed field can be used for on-demand loading of Inline children among other uses., The Inline load field can be used to prevent immediate downloading, as well as for unloading, simply by Routes.
> Lod level_changed and Inline load fields

- test/regression-suite/test/cases/mobileShader/mobileShader.html
The mobileShader regression test is pointing to the wrong x3dom js file:
`<script type='text/javascript' src='http://www.x3dom.org/download/dev/x3dom.js'></script>`
All the other files in this folder point to:
`<script type="text/javascript" src="../../../../x3dom_include.js"></script>`
Test confirmed working ok after change.
> Fixes #879 Point mobileShader test to correct js file.

- test/benchmark/field_tests.html
While attempting to run though and learn about some of x3dom's tests I found field_tests.html would fail with console error:
`x3dom.SFVec3f is not a constructor`
@andreasplesch has advised :
> The benchmark/field_test.html could be updated but I think it has not been used in a long time.
Even though this test may not be valid/used for a long time I thought it worth fixing as it was a v.simple fix. At least it now works even if no longer used.
Test (console) output:
```
4 5 6
60 4 5 6
63 1 2 3
66 4
69 1 2 3 4 5 6
71 7,8,9 1 2 3 4 5 6
73 1 2 3 4 5 6
75 122
```
> Fix test/benchmark/field_tests.html

- src/fields.js
Fixes Issue #720.
Correct rotationX(), rotationY(), and rotationZ() @param type from x3dom.fields.SFVec3f to Number.
> Correct @param type for fields.js rotation functions.

- src/Docs.js
- src/Internals.js
- src/fields.js
Both are JsDoc tags are valid however there is mixed use across the code base. The majority are `@returns` so this PR changes the few `@return` to standardise.
Also see: http://usejsdoc.org/tags-returns.html
> Standardise to use @returns (rather than @return) in JsDoc.

- src/gfx_webgl.js
- src/nodes/Geometry3D/BufferAccessor.js
- src/nodes/Geometry3D/BufferGeometry.js
- src/nodes/Geometry3D/BufferView.js
- src/util/glTF/glTF2Loader.js
- tools/packages.json
Closes #898. 
> Since buffers are used not just for geometry but also other data such as animation data, renaming the BufferGeometryAccessor/View nodes to bufferAccessor/View would allow use of those more generally.
This is just a find and replace renaming of occurrences of
* `BufferGeometryView` to `BufferView`
* `buffergeometryview` to `bufferview`
* `BufferGeometryAccessor` to `BufferAccessor`
* `buffergeometryaccessor` to `bufferaccessor`
Tested various regression-suite tests and the run fine.
As the intention is to re-use the buffer for more than just geometry, I was wondering if you also wanted these files moving out of the `nodes/Geometry3D/` folder? Possibly into a new `nodes/Buffer/` folder? Or into `nodes/Core/`?
> BufferGeometry Renaming

- src/util/Utils.js
CrossOrigin was set to "anonymous" when port was different then 80 on domain. It caused that cookie was not send with request about texture.
It did not work only for Safari.
> Texture does not load when authorization required for port different then 80 (Safari)

- src/Viewarea.js
in action here:
https://raw.githack.com/andreasplesch/x3dom/a735710b8b184e5807aa0a18ad5e5f7d7fd0076b/test/functional/inline-gltf.html
The headlight control sets 'on' to false, and 'headlight' to true
only in effect for new model, fixed by #926
> respect 'on' field for env. light

- src/nodes/VolumeRendering/MPRPlane.js
- src/nodes/VolumeRendering/MPRVolumeStyle.js
- tools/packages.json
Extension to the _MPRVolumeStyle_ of the volume rendering component that allows to define multiple reconstruction planes using a new node: _MPRPlane_. Refs #944
Example scene witth multiple planes defined:
```xml
<X3D>
<Scene>
<Background skyColor='1.0 1.0 1.0'></Background>
<Viewpoint position='1.9 1.7 -1.4' orientation='0.9 -0.4 0.2 4.1'	zNear='0.001' zFar='100'></Viewpoint>
<VolumeData id='volume' dimensions='1 1 1' render='true'>
<ImageTextureAtlas containerField='voxels' url='aorta4096.png' numberOfSlices='96' slicesOverX='10' slicesOverY='10'></ImageTextureAtlas>
<MPRVolumeStyle forceOpaque="true">
<MPRPlane normal='0.0 1.0 0.0' position='0.5'></MPRPlane>
<MPRPlane normal='1.0 0.0 0.0' position='0.5'></MPRPlane>
<MPRPlane normal='0.0 0.0 1.0' position='0.5'></MPRPlane> …
```
> Allowing to define multiple arbitrary MPR planes

- doc/x3doc/base/author/configuration.html
- src/Main.js
Updated Scene Author - Configuration documentation (https://doc.x3dom.org/author/configuration.html):
* Added new useGeoCache option added by #968.
* Fixed a couple of missing closing html tags + typo + quick run though prettifier.
* Also added a number of other missing config parameters found in Main.js - I need some help to fill in some of the ?? gaps as some of these I don't know what they do?
While doing this I noticed the now deprecated options 'flashrenderer' and 'swfpath' were no longer referenced anywhere in code, so I have removed these from the Main.js validParams list.
> Configuration Documentation updates - added useGeoCache & others

- src/fields.js
This PR makes improvements to the color parse functions:
* Adds parsing support for `rgb()` and `rgba()` CSS colors.
* Makes more DRY.
* Consolidate `fields.SFColor.colorParse()` and `fields.SFColorRGBA.colorParse()` to single function.
* Slight tidy of variables.
> Field Color Parse Improvements

- src/Texture.js
- src/nodes/Texturing/PixelTexture.js
- src/nodes/Texturing/X3DTextureNode.js
- test/functional/channelCount/index.html
use pixel texture image component number as origChannelCount if not provided. See example:
https://raw.githack.com/x3dom/x3dom/b7f18aa70bd3501066b4b95b710a4afe408cbf67/test/functional/channelCount/index.html
> PixelTexture auto channel count

- src/nodes/NURBS/NurbsCurve.js
- src/nodes/NURBS/x3dom-nurbs-web-worker.js
Weights where not taken into account when evaluating points of NURBS curves
and surfaces, leading to incorrect tessellations when one or more weights
were different from the default value of 1.0.
Problem is solved by multiplying the control points coordinates by the
weights in the numerator part of the formula.
> fix for #1059: incorrect tessellation of rational NURBS

- src/nodes/NURBS/NurbsCurve.js
- src/nodes/NURBS/x3dom-nurbs-web-worker.js
Although the X3D specification is not cristal clear, many other X3D viewers
expect the control points to be pre-multiplied. To have that same behavior,
we undo the change, assuming that the control points are pre-multiplied
at authoring time.
> Undo fix for #1059: incorrect tessellation of rational NURBS

- src/util/Utils.js
as performance.now is always available since https://github.com/x3dom/x3dom/commit/9e1f483d3f8e3e39385a91933d0fec4935d82cef
https://github.com/x3dom/x3dom/blob/9edcd6e2f6fb93bfddad94981131b144242b8889/src/util/Utils.js#L22-L34
> Remove new Date().getTime() fallback in start-/stopMeasure

- src/X3DCanvas.js
The CSS class `x3dom-canvas-mousedown` changes the cursor from `pointer` to `grabbing`.
The calls is added to the `canvas `in function `onMouseDown `and removed in `onMouseUp` or `onMouseOut `within `x3dom.X3DCanvas.prototype.bindEventListeners`.
However, `onMouseOut` is mispelled as `onMouseAlt`. Therefore the cursor still has form `grabbing` (even if it's not in grabbing mode anymore) when you click down on the canvas, leave the canvas, and enter the canvas again.
Some test cases use `onMouseOut`, too (in the context of individual shapes):
`\test\functional\inlineReflection.html`
Used attributes: `onmouseover`, `onmouseout `
Expected result: The color of the shapes changes depending on position of mouse pointer.
`/test/regression-suite/test/cases/depthVolren/depthVolren.html`
Used …
> Replace misspelled onMouseAlt with onMouseOut

- src/nodes/Geometry2D/Arc2D.js
- src/nodes/Geometry2D/ArcClose2D.js
- src/nodes/Lighting/SpotLight.js
- src/nodes/Navigation/X3DViewpointNode.js
- src/util/VRControllerManager.js
I'm always confused when I see 'magic' numbers in code. 
What is the meaning of `1.57`?
Does this represent 90° or approximately 90° (because high precision does not matter) or a little bit less than 90° (which might be important to avoid singularity issues)?
In the code we mostly see `Math.PI / 2` instead and sometimes `Math.PI / 2.0` (which looks better as it's a float anyway). 
Therefore I've replaced the remaining different constants `1.57`, `1.570796`, `1.5707963`, `1.57079633` by `Math.PI / 2.0` 
(Exception: in ShaderDynamic.js the constants are required for the gl command string.)
Limited test: My program is still working and it's using some of these pieces of code. However, I've no idea how to produce test cases for all changes.
> Replace 1.5707963 with Math.PI

- src/Docs.js
X3DOM implements X3D v 3.3.
The specification of X3D had moved to https://www.web3d.org/documents/specifications/19775-1/V3.3
I've checks all links and added the chapter number and title as comments.
> Update link x3dom.docs.specBaseURL

- src/Viewarea.js
- src/gfx_webgl.js
- src/util/Utils.js
Concerning pick mode:
"color" shows the RGB colors.
"idbuf", "idbuf24", "box" show the position.
"idbufid", "texcoord" don't show the position, therefore I decided to name it simply 'data'.
Concerning Background node:
It is not useful to show the sum count of explicit plus implicit colors or angels - the user would not recognize and understand these numbers. However, it might help to explain how to correct the data.
This condition has to be true:
(skyAngle.lenght == skyColor.length - 1) && (groundAngle.length == groundColor.length -1)
> Extend log messages

- src/Runtime.js
Axis  definition "negY" evaluates to ( 1, -1,  0 ) instead of ( 0, -1,  0 ).
In addition we could think about accepting axis definitions directly instead of symbolic names like "negY": In the default case of the switch statement we could check if parameter axis has type `SFVec3f` or can be resolved to this type. Well, that would be an extension of the API which requires corresponding documentation. And in this case we should do the same in `x3dom.Viewarea.prototype.showAll`.
> Correct axis definition "negY"

- src/Runtime.js
- src/fields.js
- src/nodes/EnvironmentalEffects/Background.js
- src/nodes/EnvironmentalEffects/X3DBackgroundNode.js
- src/nodes/Geometry3D/Sphere.js
- src/nodes/Navigation/NavigationInfo.js
While analyzing x3dom, i.e. about defining background cube pictures and about copying ideas from the helicopter mode for my own navigation mode, I made some comments into the documentation which might be useful for the master, too.
- The background cube is defined in x3d, it's not added by x3dom. 
see 
https://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/components/enveffects.html#Background
- I didn't found a way to use the `scaling` attribute of the `Background` note but a least I can state, that's a boolean attribute.
see `gfx_webgl.js`
`if ( bgnd._vf.scaling && bgnd._webgl.texture.ready )` ...
- The array attribute `typeParams`  of the `NavigationInfo` note has up to 7 values.
side remarks:
The scaling of the background cube pictures seemed to have changed between …
> Small documentation updates

- src/shader/ShaderDynamic.js
Hi!
I'm rendering gltf meshes with transparent textures or materials and was wondering why they are not rendering until I changed the value of alphaCutoff. According to the documentation the alphaCutoff should only be used in case alphaMode is "MASK"  [1][2], but it is also used in "BLEND".
After removing the last else clause of:
https://github.com/x3dom/x3dom/blob/cdadbc1c01d3c04989c0bb7176032c90eddca466/src/shader/ShaderDynamic.js#L1310-L1324
my objects got rendered correctly. 
[1] https://doc.x3dom.org/developer/x3dom/nodeTypes/PhysicalMaterial.html
[2] https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/AlphaBlendModeTest/README.md
> Use alphaCutoff only in 'MASK' alphaMode as according to spec

- src/nodes/RigidBodyPhysics/RigidBodyPhysics.js
see #1193 
Other guards may be required as well.
> CollidableShape: add two guards to avoid errors

- CHANGELOG.md
- src/X3DDocument.js
- src/nodes/Core/X3DNode.js
- src/nodes/Followers/X3DFollowerNode.js
- src/nodes/Grouping/X3DTransformNode.js
- src/nodes/Lighting/X3DLightNode.js
- src/nodes/Texturing/RenderedTexture.js
- src/nodes/Time/TimeSensor.js
regarding issue:
https://github.com/x3dom/x3dom/issues/1200
Summary:
sometimes `this._nameSpace` is `null`
Changes:
Check if `_nameSpace` exists, and that `doc` is found, before proceeding, so the script wont crash
> Check if findX3DDoc() succeeds

- CHANGELOG.md
- src/util/glTF/glTF2Loader.js
if the property exists and includes an extension which is not supported then abort loading with a warning.
> support glTF extensionsRequired property
